name: Build WordPress Plugin Release

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Release Zip
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Get version from plugin file
        id: plugin-version
        run: |
          VERSION=$(awk -F"'" '/Version:/ {print $2}' chip-for-tour-master.php)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "Detected version: ${VERSION}"
        
      - name: Create zip file
        run: ${{ github.action_path }}/build-zip.sh
          