name: Plugin Activation Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  activation-test:
    name: Test Plugin Activation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup WordPress test environment
      uses: 10up/action-wordpress-tests@v1
      with:
        version: 'latest'
    
    - name: Install WordPress
      run: |
        wp core download --version=latest --path=/tmp/wordpress
        wp config create --dbname=wordpress_tests --dbuser=root --dbpass=root --dbhost=127.0.0.1 --path=/tmp/wordpress
        wp core install --url=http://example.com --title="Test" --admin_user=admin --admin_password=password --admin_email=admin@example.com --path=/tmp/wordpress
    
    - name: Copy plugin to WordPress
      run: |
        mkdir -p /tmp/wordpress/wp-content/plugins/chip-for-tour-master
        cp -R . /tmp/wordpress/wp-content/plugins/chip-for-tour-master/
    
    - name: Test plugin activation
      run: |
        wp plugin activate chip-for-tour-master --path=/tmp/wordpress

    - name: PHP Compatibility Check
      run: |
        composer require phpcompatibility/php-compatibility
        ./vendor/bin/phpcs --standard=PHPCompatibility --extensions=php --runtime-set testVersion 7.4- .
